// to-do: move to process.env
export const Config = {
  adminColdFusionUrl: 'http://devcloudadmin.hme.com/',
  coldFusionUrl: 'https://engdev.hmedtcloud.com/',
  // apiBaseUrl: 'http://localhost:7071/', // 'https://hme-dev-public-cloud-func.azurewebsites.net/',
  // authBaseUrl: 'http://localhost:7072/', //https://hme-dev-public-cloud-func.azurewebsites.net

  apiBaseUrl: 'https://hme-dev-public-cloud-func.azurewebsites.net/',
  authBaseUrl: 'https://hme-dev-public-cloud-func.azurewebsites.net/',
  tokenPath: 'api/func-auth?code=dd4nGGaJ5f7NBP3quIE3v68e0as4dOPDYDz/cVxGeg9KwFbpqRYQNg==',
  // tokenPath: 'api/func-auth',
  token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkZTaW11RnJGTm9DMHNKWEdtdjEzbk5aY2VEYyIsImtpZCI6IkZTaW11RnJGTm9DMHNKWEdtdjEzbk5aY2VEYyJ9.eyJhdWQiOiJzcG46MDAwMDAwMDItMDAwMC0wMDAwLWMwMDAtMDAwMDAwMDAwMDAwIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvYjk3ZDMyZTctMjNhNS00NGQ3LWI0NDItYzg1ZTZmMDNkOTYyLyIsImlhdCI6MTUyMzg5NTg5NiwibmJmIjoxNTIzODk1ODk2LCJleHAiOjE1MjM4OTk3OTYsImFjciI6IjEiLCJhaW8iOiJBU1FBMi84SEFBQUFLRzdqVFpLanlxVWtuWm5SMVlpVmJ3Qzhhc1JTUVBndG9EQTNNWER4UkxzPSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiIyY2YzMjU5MC0wNmMxLTQ1MWMtOWM5My1iZTI2Mzc2MDI3ZjUiLCJhcHBpZGFjciI6IjAiLCJlX2V4cCI6MjYyODAwLCJmYW1pbHlfbmFtZSI6IksiLCJnaXZlbl9uYW1lIjoiU2VsdmVuZHJhbiIsImlwYWRkciI6IjE2NC4xNjQuMTEuMiIsIm5hbWUiOiJTZWx2ZW5kcmFuIEsiLCJvaWQiOiJkMmZlNWVkMy1kM2U0LTQ1OGItODZmYy05MDkxMWYzNzRkNTYiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtMzE1NTIwNDE0LTU0OTQxOTM0Ny02MjE2OTYyMTQtNDgwOTIiLCJwdWlkIjoiMTAwMzdGRkVBOEZEQkEzMCIsInNjcCI6IkRpcmVjdG9yeS5BY2Nlc3NBc1VzZXIuQWxsIFVzZXIuUmVhZCBVc2VyLlJlYWRCYXNpYy5BbGwiLCJzdWIiOiItTVBCVlhNeEZyb0h6bEljNkljVnpJeTRVTGpYZ0d4RklpV1hyYkpsR2owIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6Ik5BIiwidGlkIjoiYjk3ZDMyZTctMjNhNS00NGQ3LWI0NDItYzg1ZTZmMDNkOTYyIiwidW5pcXVlX25hbWUiOiJub3VzLXNlbHZhQEhNRS5DT00iLCJ1cG4iOiJub3VzLXNlbHZhQEhNRS5DT00iLCJ1dGkiOiJIdU1EZEFvNVoweXlWemNGaXM4bEFBIiwidmVyIjoiMS4wIn0.POnAxPTlldQHQUvN17Nj9UtPVhhCOJDK6gBgUlXL2n4wBZEm2ay4wRqhaFumPnisdopIm3RQ_bPqHoDNgp7DgW3WE9U3bll2rSNFQEG0mXerVm2_EW5RJPVriA9kikxAbbozrg3RmgMyw3BS3CfZnkprwQXABN76Db0Ha5PRSV773fsbDI7cG_xwOUUyvbi2dzhjamESwvfZOExe5Lp_DDKasGFyEReN2hHLKmetMMIHz0pwtI5DXLn4gBqRCDYRMEDfnJa144kXYjKzFbQ3Bx-EutgHyLxq0IWm13OtnJZ-3ars-RLctXUVkiEv2WLF_zvPPELsNmMcagoV_xPo8g',
  ctxToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyX0lEIjoxLCJVc2VyX1VJRCI6IjY4TEtCUDg1QzFTS0gxRkkzTTdYNDBDSkhLR1UwN0ZaIiwiVXNlcl9Pd25lckFjY291bnRfSUQiOjEzNTcsIlVzZXJfQ29tcGFueV9JRCI6MTI3MSwiVXNlcl9FbWFpbEFkZHJlc3MiOiJhYmhyYWRpcHJAbm91c2luZm8uY29tIiwiVXNlcl9GaXJzdE5hbWUiOiInIiwiVXNlcl9MYXN0TmFtZSI6IlJ1ZHJhIiwiaWF0IjoxNTIzODk1MzYzLCJleHAiOjE1MjM5ODE3NjN9.ujp2Vm86uss2fZyWlE_KSdTReHUJfUKk7sSmigCoGqU'
}
