import * as StoreDetailsPopup from '../actionTypes/StoreDetailsPopup/storeDetailsPopup'

export const closePopup = () => {
  return {
    type: 'CLOSE_POPUP',
    payload: null
  }
}

export const initModal = () => {
  return {
    type: StoreDetailsPopup.INIT_STORE_POPUP,
    payload: {
      'storeDetails': {
        'Brand_Name': "McDonald's",
        'Store_Number': '303',
        'Store_Name': null,
        'Store_AddressLine1': '',
        'Store_AddressLine2': '',
        'Store_AddressLine3': '',
        'Store_AddressLine4': '',
        'Store_PhoneNumber': '',
        'Store_FaxNumber': '',
        'Store_Locality': '',
        'Store_Region': '',
        'Store_PostCode': '',
        'Country_ID': 1,
        'Country_Name': 'United States',
        'Group_ID': null,
        'Group_Name': 'Drive-thru',
        'GroupName': null,
        'User_EmailAddress': 'tpstorytester+303@gmail.com',
        'timeZone': [
          '(GMT) Coordinated Universal Time',
          '(GMT+00:00) Casablanca',
          '(GMT+00:00) Dublin, Edinburgh, Lisbon, London',
          '(GMT+00:00) Monrovia, Reykjavik',
          '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
          '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
          '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',
          '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
          '(GMT+01:00) West Central Africa',
          '(GMT+01:00) Windhoek',
          '(GMT+02:00) Amman',
          '(GMT+02:00) Athens, Bucharest',
          '(GMT+02:00) Beirut',
          '(GMT+02:00) Cairo',
          '(GMT+02:00) Chisinau',
          '(GMT+02:00) Damascus',
          '(GMT+02:00) Gaza, Hebron',
          '(GMT+02:00) Harare, Pretoria',
          '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
          '(GMT+02:00) Jerusalem',
          '(GMT+02:00) Kaliningrad',
          '(GMT+02:00) Tripoli',
          '(GMT+03:00) Baghdad',
          '(GMT+03:00) Istanbul',
          '(GMT+03:00) Kaliningrad, Minsk',
          '(GMT+03:00) Kuwait, Riyadh',
          '(GMT+03:00) Minsk',
          '(GMT+03:00) Moscow, St. Petersburg, Volgograd',
          '(GMT+03:00) Nairobi',
          '(GMT+03:30) Tehran',
          '(GMT+04:00) Abu Dhabi, Muscat',
          '(GMT+04:00) Baku',
          '(GMT+04:00) Izhevsk, Samara',
          '(GMT+04:00) Port Louis',
          '(GMT+04:00) Tbilisi',
          '(GMT+04:00) Yerevan',
          '(GMT+04:30) Kabul',
          '(GMT+05:00) Ashgabat, Tashkent',
          '(GMT+05:00) Ekaterinburg',
          '(GMT+05:00) Islamabad, Karachi',
          '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
          '(GMT+05:30) Sri Jayawardenepura',
          '(GMT+05:45) Kathmandu',
          '(GMT+06:00) Astana',
          '(GMT+06:00) Dhaka',
          '(GMT+06:00) Omsk',
          '(GMT+06:30) Yangon (Rangoon)',
          '(GMT+07:00) Bangkok, Hanoi, Jakarta',
          '(GMT+07:00) Hovd',
          '(GMT+07:00) Krasnoyarsk',
          '(GMT+07:00) Novosibirsk',
          '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
          '(GMT+08:00) Irkutsk',
          '(GMT+08:00) Krasnoyarsk',
          '(GMT+08:00) Kuala Lumpur, Singapore',
          '(GMT+08:00) Perth',
          '(GMT+08:00) Taipei',
          '(GMT+08:00) Ulaanbaatar',
          '(GMT+08:30) Pyongyang',
          '(GMT+08:45) Eucla',
          '(GMT+09:00) Chita',
          '(GMT+09:00) Irkutsk',
          '(GMT+09:00) Osaka, Sapporo, Tokyo',
          '(GMT+09:00) Seoul',
          '(GMT+09:00) Yakutsk',
          '(GMT+09:30) Adelaide',
          '(GMT+09:30) Darwin',
          '(GMT+10:00) Brisbane',
          '(GMT+10:00) Canberra, Melbourne, Sydney',
          '(GMT+10:00) Guam, Port Moresby',
          '(GMT+10:00) Hobart',
          '(GMT+10:00) Vladivostok',
          '(GMT+10:00) Yakutsk',
          '(GMT+10:30) Lord Howe Island',
          '(GMT+11:00) Bougainville Island',
          '(GMT+11:00) Chokurdakh',
          '(GMT+10:00) Magadan',
          '(GMT+11:00) Norfolk Island',
          '(GMT+11:00) Sakhalin',
          '(GMT+11:00) Solomon Is., New Caledonia',
          '(GMT+11:00) Vladivostok',
          '(GMT+12:00) Anadyr, Petropavlovsk-Kamchatsky',
          '(GMT+12:00) Auckland, Wellington',
          '(GMT+12:00) Coordinated Universal Time+12',
          '(GMT+12:00) Fiji',
          '(GMT+12:45) Chatham Islands',
          "(GMT+13:00) Nuku'alofa",
          '(GMT+13:00) Samoa',
          '(GMT+14:00) Kiritimati Island',
          '(GMT-01:00) Azores',
          '(GMT-01:00) Cabo Verde Is.',
          '(GMT-02:00) Coordinated Universal Time-02',
          '(GMT-02:00) Mid-Atlantic',
          '(GMT-03:00) Araguaina',
          '(GMT-03:00) Brasilia',
          '(GMT-03:00) Cayenne, Fortaleza',
          '(GMT-03:00) City of Buenos Aires',
          '(GMT-03:00) Greenland',
          '(GMT-03:00) Montevideo',
          '(GMT-03:00) Saint Pierre and Miquelon',
          '(GMT-03:00) Salvador',
          '(GMT-03:30) Newfoundland',
          '(GMT-04:00) Asuncion',
          '(GMT-04:00) Atlantic Time (Canada)',
          '(GMT-04:00) Cuiaba',
          '(GMT-04:00) Georgetown, La Paz, Manaus, San Juan',
          '(GMT-04:00) Santiago',
          '(GMT-04:00) Turks and Caicos',
          '(GMT-04:30) Caracas',
          '(GMT-05:00) Bogota, Lima, Quito, Rio Branco',
          '(GMT-05:00) Chetumal',
          '(GMT-05:00) Eastern Time (US & Canada)',
          '(GMT-05:00) Haiti',
          '(GMT-05:00) Havana',
          '(GMT-05:00) Indiana (East)',
          '(GMT-06:00) Central America',
          '(GMT-06:00) Central Time (US & Canada)',
          '(GMT-06:00) Easter Island',
          '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
          '(GMT-06:00) Saskatchewan',
          '(GMT-07:00) Arizona',
          '(GMT-07:00) Chihuahua, La Paz, Mazatlan',
          '(GMT-07:00) Mountain Time (US & Canada)',
          '(GMT-08:00) Baja California',
          '(GMT-08:00) Coordinated Universal Time-08',
          '(GMT-08:00) Pacific Time (US & Canada)',
          '(GMT-09:00) Alaska',
          '(GMT-09:00) Coordinated Universal Time-09',
          '(GMT-09:30) Marquesas Islands',
          '(GMT-10:00) Aleutian Islands',
          '(GMT-10:00) Hawaii',
          '(GMT-11:00) Coordinated Universal Time-11',
          '(GMT-12:00) International Date Line West',
          '(GMT+06:00) Novosibirsk',
          '(GMT+04:00) Astrakhan, Ulyanovsk',
          '(GMT+07:00) Barnaul, Gorno-Altaysk',
          '(GMT+07:00) Tomsk'
        ]
      },
      'deviceDetails': {
        'EOS': [
          {
            'Device_Name': 'EOS',
            'Device_UID': '60A980CE-3038-4B3F-9495-BB3F61EEEC88',
            'Device_IsActive': 0,
            'Device_SettingVersion': 'A.2.01',
            'Device_SerialNumber': '',
            'Device_MainVersion': '2.01.17',
            'Store_Number': '303',
            'Brand_Name': "McDonald's"
          },
          {
            'Device_Name': 'EOS',
            'Device_UID': 'D8B1E421-C70A-4A8D-ABD7-7E32F2BA2D2A',
            'Device_IsActive': 1,
            'Device_SettingVersion': 'A.2.01',
            'Device_SerialNumber': '',
            'Device_MainVersion': '2.01.17',
            'Store_Number': '303',
            'Brand_Name': "McDonald's"
          }
        ],
        'CIB': [
          {
            'Device_Name': 'CIB',
            'Device_UID': 'C21D60C3-C63A-43C7-A5A6-D56048B8AAE4',
            'Device_IsActive': 1,
            'Device_SettingVersion': 'A2.12.2',
            'Device_SerialNumber': 'AZUREUAT2',
            'Device_MainVersion': '2.12.12',
            'Store_Number': '303',
            'Brand_Name': "McDonald's",
            'Email': 'tpstorytester+303@gmail.com'
          }
        ],
        'ZOOM': [
          {
            'Device_Name': 'ZOOM',
            'Device_UID': 'F141D470-960D-4B99-A52A-7001700820F6',
            'Device_IsActive': 1,
            'Device_SettingVersion': 'A.2.00',
            'Device_SerialNumber': '00000304',
            'Device_MainVersion': '2.31.7.999',
            'Store_Number': '303',
            'Brand_Name': "McDonald's"
          }
        ]
      },
      'status': true
    }
  }
}
